language: elixir

elixir:
  - '1.12.1'

otp_release:
  - '24.0'

services:
  - 'postgresql'

addons:
  postgresql: "13"
  apt:
    packages:
    - postgresql-13
    - postgresql-client-13
env:
  global:
  - PGPORT=5433
  - PGUSER=travis

before_script:
  - psql --version
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"
  - cp config/travis.exs config/test.exs
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate

cache:
  directories:
    - _build
    - deps
